# Generated by Django 4.2.28 on 2026-02-13 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_ip', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BitTorrentPackets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('bittorrent_metadata', models.CharField(max_length=255)),
                ('net_packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_packet_bittoreent_packets', to='base.networkpacket')),
            ],
        ),
    ]
