# Generated by Django 4.2.28 on 2026-02-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BitTorrentPackets',
            new_name='BitTorrentPacket',
        ),
    ]
