# Generated by Django 4.2.28 on 2026-02-13 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_bittorrentpackets_bittorrentpacket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkpacket',
            options={'ordering': ('source_ip',)},
        ),
        migrations.AlterField(
            model_name='bittorrentpacket',
            name='net_packet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_packet_bittorrent_packet', to='base.networkpacket'),
        ),
    ]
