# Generated by Django 4.2.28 on 2026-02-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_networkpacket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkpacket',
            name='info_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
