# Generated by Django 4.2.28 on 2026-02-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_networkpacket_info_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bittorrentpacket',
            name='bittorrent_metadata',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
