# Generated by Django 4.2.28 on 2026-02-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_bittorrentpacket_bittorrent_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bittorrentpacket',
            name='bittorrent_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
