# Generated by Django 4.2.28 on 2026-02-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_bittorrentpacket_bittorrent_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNetworkPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('source_port', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_port', models.CharField(blank=True, max_length=255, null=True)),
                ('transport_protocol', models.CharField(blank=True, max_length=255, null=True)),
                ('protocol', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.CharField(blank=True, max_length=2000, null=True)),
                ('payload_dict', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
