# Generated by Django 4.2.28 on 2026-02-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_basenetworkpacket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basenetworkpacket',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
