# Generated by Django 4.2.28 on 2026-02-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_basenetworkpacket_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_packets', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_dht_packets', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tracker_packets', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pwp_packets', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_piece_packets', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_info_hashes_packets', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
